### ISSUE TITLE
About the output.txt rules

### ISSUE THREAD

**Issue by jackhftang** [mingchuno/ABCDEFGHPPP#57]
I have just see this. 

```
output.txt rules

All output.txt in Advance-XXX MUST include the following information

Total number of solutions
First 50 solutions
Time used for calculation & Machine used
(for Base N) include all N = 10, 16, 22, 28, 34 result
```

50 is too few to say an algorithm is correct and test the speed (what if I just output 50 solutions then exit?) You may say it require to find the total number of solution, but finding the number of solutions is not the same as finding the exact solutions, which the former could use different analysis/algorithm.

**Comment by jackhftang** [comment]
suggest print out all solution in specific format and order e.g. 
first line is a number N which is the total number of solution, then follow N lines, each line in the following form AB-CD->EF+GH->PPP (no space) and arrange in lexicographical order.

Also, named sol_w2_b38.txt means that this is solution in base-38 with width-2

**Comment by jackhftang** [comment]
Time used for calculation & Machine used is highly varying. maybe wrote in an other file for reference only.

**Comment by gaplo917** [comment]
@jackhftang  For `width = 2`  Base 34 , there are [210k solutions](https://github.com/mingchuno/ABCDEFGHPPP/blob/master/Advance-base/scala-baseN-optimized-parallel/output.txt). 

That is too much for print it out. First 50 solutions are just for show case.

The most important are the correctness & efficiency. 

Also, I strongly disagree to print the solution directly during running because I/O is slow...

And if we assume that programmer can solve `width =2`, then they should be able to solve `width = 3,4,5,6,7...`. That's why you can write generic for your javascript version.

I think for the "Advance" part, no body will care about the solutions ( coz there are toooooo many). Again, Correctness & Clean code & Efficiency always go for the first.  

So, IMHO, solving `width = 4` is enough to demonstrate the algorithm comprehensively.

**Comment by xnastudio** [comment]
Did anyone solve this? 

Base 17 ABCD - EFGH = IJKL, IJKL + MNOP = QQQQQ

**Comment by jackhftang** [comment]
Base 25 啦

**Comment by gaplo917** [comment]
@xnastudio 

Seems that @jackhftang has solved in javascript version.  Just wait for his Pull request to merge

**Comment by xnastudio** [comment]
The best I can solve is:

Base 34 AB - CD = EF, EF - GH = PPP (Width = 2)

**Comment by gaplo917** [comment]
@jackhftang s' solution is lightening fast on solving `Base 34 AB - CD = EF, EF - GH = PPP (Width = 2)`, 

@xnastudio should take a look, how he archive this!!!  and compared with your's solution
